menu:
- {name: 'blog', url: '/blog'}
- {name: 'codes', url: '/codes'}
- {name: 'replications', url: '/replications'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/sharonsthomas'}
- {icon: 'twitter', link: 'https://x.com/shrn_st07'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/sharon-st07/'}

contacts:
- {name: 'Sharon Thomas', title: 'Research Associate', department: 'Accounting', institution: 'Indian School of Business', institution_address: 'Gachibowli, Hyderabad, India - 500032', phone: '(000) 000-0000', email: 'SharonSunny_Thomas@isb.edu', office: 'Academic Centre 4, Wing A', image: 'assets/img/contact.jpg'}
